// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gacvkysgaqglflvoxdlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhY3ZreXNnYXFnbGZsdm94ZGx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDYzNzMsImV4cCI6MjA2NTU4MjM3M30.3tH1KTLwMbAbCMtDzFUvqS4sUl-5z1HR6kH6ASL4K4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);